require_relative 'array-wrapper/ArrayWrapper.rb'
require_relative 'array-wrapper/Flags.rb'
require_relative 'array-wrapper/Includes.rb'
require_relative 'array-wrapper/InstallPkgList.rb'
require_relative 'array-wrapper/Libs.rb'
require_relative 'array-wrapper/Requirements.rb'
require_relative 'array-wrapper/Sources.rb'
require_relative 'array-wrapper/Track.rb'