require_relative 'c8/Config.rb'
require_relative 'c8/Erb.rb'
require_relative 'c8/Password.rb'
require_relative 'c8/Pty.rb'
require_relative 'c8/Puts.rb'
require_relative 'c8/Sh.rb'
require_relative 'c8/Task.rb'